name: Build altinput

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clone altinput repository
      run: git clone https://github.com/AltimorTASDK/altinput.git

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build altinput
      run: msbuild altinput/tgm3_input.sln /p:PlatformToolset=v143 /p:Configuration=Release
